# This is a basic workflow to help you get started with Actions
name: PHP 8.0 Alpine builds

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  php-80:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push PHP 8.0 CLI
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: ./versions/8.0/alpine3.15/base-cli
          push: true
          tags: mallardduck/base-php:8.0-cli-alpine
      -
        name: Build and push PHP 8.0 FPM
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: ./versions/8.0/alpine3.15/base-fpm
          push: true
          tags: mallardduck/base-php:8.0-fpm-alpine
      -
        name: Build and push PHP 8.0 cache
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: ./versions/8.0/alpine3.15/cache
          push: true
          tags: mallardduck/base-php:8.0-cache-alpine
      -
        name: Build and push PHP 8.0 MySQL
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: ./versions/8.0/alpine3.15/mysql
          push: true
          tags: mallardduck/base-php:8.0-mysql-alpine
      -
        name: Build and push PHP 8.0 Swoole
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: ./versions/8.0/alpine3.15/swoole
          push: true
          tags: mallardduck/base-php:8.0-swoole-alpine
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
